# reference: https://k3d.io/v5.4.6/usage/configfile/
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: notraefik
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer
options:
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - server:*